# Generated by Django 5.2 on 2025-07-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('courses', models.JSONField(default=list)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
