# Generated by Django 5.2 on 2025-07-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=20)),
                ('professor', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('a_plus', models.IntegerField()),
                ('a', models.IntegerField()),
                ('a_minus', models.IntegerField()),
                ('b_plus', models.IntegerField()),
                ('b', models.IntegerField()),
                ('b_minus', models.IntegerField()),
                ('c_plus', models.IntegerField()),
                ('c', models.IntegerField()),
                ('c_minus', models.IntegerField()),
                ('d_plus', models.IntegerField()),
                ('d', models.IntegerField()),
                ('d_minus', models.IntegerField()),
                ('f', models.IntegerField()),
                ('w', models.IntegerField()),
                ('other', models.IntegerField()),
            ],
        ),
    ]
