# Generated by Django 5.2 on 2025-07-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.TextField()),
                ('course_number', models.CharField(max_length=10)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('average_gpa', models.FloatField(blank=True, null=True)),
                ('is_recent', models.BooleanField(default=True)),
                ('name', models.TextField(unique=True)),
                ('professors', models.JSONField(default=list)),
            ],
        ),
    ]
